name: Docker Build and Push

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} 
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/${{ matrix.arch }} -t $DOCKER_USERNAME/xmake:${{ matrix.arch }} .

    - name: Login to Docker Hub
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Push Docker image to Docker Hub
      run: docker push $DOCKER_USERNAME/xmake:${{ matrix.arch }}
